# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ydeo90OHigegWLYSUlVX5tXjPNxjXpPu
"""

import streamlit as st
st.write('hello world')

# load warehouse data

import pandas as pd
import streamlit as st

st.title('warehous KPI dashboard')

df = pd.read_csv('warehouse_data.csv')

st.write(df.head())

#add KPIs

total_orders = df['orders'].sum()
total_inventory = df['inventory_qty'].sum()
avg_lead_time = df['lead_time'].mean()

st.metric('Total Orders', total_orders)
st.metric('Total Inventory', total_inventory)
st.metric('Avg Lead Time', round(avg_lead_time,2))

# Add Chart

import matplotlib.pyplot as plt

# Orders trend
# Create a figure and an axes object for the plot
fig, ax = plt.subplots()

# Group by the correct 'date' column and plot onto the created axes
df.groupby('date')['orders'].sum().plot(ax=ax)

st.subheader('Orders Trend')
st.pyplot(fig)

#Add filters (Interactive dashboard)

warehouse = st.selectbox('Select warehouse', df['warehouse'].unique())

filtered_df = df[df['warehouse'] == warehouse]

st.write(filtered_df)

#Slow-Moving Inventory KPI

slow_moving = df[df['inventory_days'] > 60]['inventory_qty'].sum()

st.metric('Slow Moving Inventory', slow_moving)

# make it look professional

col1, col2, col3 = st.columns(3)
col1.metric('Total Orders', total_orders)
col2.metric('Total Inventory', total_inventory)
col3.metric('Avg Lead Time', round(avg_lead_time,2))

!streamlit run dashboard.py